<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GarageInventory.Persistence\GarageInventory.Persistence.csproj" />
    <ProjectReference Include="..\GarageInventory.Shared\GarageInventory.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Converters\Tires\" />
    <Folder Include="Models\MotorParts\" />
    <Folder Include="Models\Сlothes\" />
    <Folder Include="Models\Tools\" />
    <Folder Include="Models\Tires\" />
  </ItemGroup>

</Project>
